#!/bin/bash

USAGE="usage: $(basename "$0") [url] [command]"

if [[ $# -lt 2 ]]; then
    echo "$USAGE"
    exit 1
fi

LIGHTSWITCH_URL=$1

if [[ $(curl --silent --head --output /dev/null --write-out "%{http_code}" "$LIGHTSWITCH_URL") = "200" ]]; then
    exec "${@:2}"
fi
